name: "CI: build and test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  run-build-and-test:
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install .net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Checkout main
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
